# This is the configuration file for Decap CMS.
# It tells the CMS how to interact with your GitHub repository.

backend:
  name: github
  repo: zicoabhidey/test1234 # IMPORTANT: Change this to your GitHub repo
  branch: main # The branch to update
  
# This is where the media (e.g., images) uploaded via the CMS will be stored.
media_folder: "assets/uploads" 
public_folder: "/assets/uploads"

# This defines the "collections" of content you can create.
# Here, we're just defining one collection: "Blog Posts".
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog Posts" # Used in the UI
    folder: "_posts" # The folder in your repo where the content files will be stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template
    fields: # The fields for each document, which form the GUI
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string", default: "Admin" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
